# App title
title: Weather Anomaly Viewer

# The `variables` object defines important information about each variable. Its
# keys must be exactly the set `precip`, `tmin`, `tmax`.
variables:
  precip:
    label: Precipitation
    units: mm/mon
    decimalPlaces: 1
  tmin:
    label: T<sub>min</sub>
    units: C
    decimalPlaces: 2
  tmax:
    label: T<sub>max</sub>
    units: C
    decimalPlaces: 2

# The `datasets` object defines important information about each dataset. Its
# keys must be exactly the set `anomaly`, `monthly`, `baseline`.
datasets:
  anomaly:
    label: Anomaly
  monthly:
    label: Monthly
  baseline:
    label: Baseline

# The `map` object defines certain features of the map appearance, except the
# colour scale.
map:
  markers:
    # Appearance of all (data, monthly, baseline) station location markers.
    location:
      color: "#222222"
      radius: 1
      weight: 1
      fillOpacity: 1
    # Appearance of data markers (the fillColour value is replaced according
    # to the station value and the colour scale definition.
    data:
      radius: 8
      color: "#999999"
      weight: 1
      fillColor: "#000000" # Replaced according to station value
      fillOpacity: 1
  # Order and labelling for the 3 marker layers.
  markerLayers:
    order:
      - data
      - monthly
      - baseline
    definitions:
      data: Data values
      monthly: Monthly station locations
      baseline: Baseline station locations

# The `colourScales` object defines a colour scale for each combination of
# variable and dataset. A colour scale defines a mapping numerical values to
# colours, and determines the colours of the data markers on the map.
#
# Specifically, a colour scale divides the real numbers into a sequence of
# contiguous intervals. Intervals are defined by a list
# of thresholds. Interval `i` is the range `threshold[i-1] < x <= threshold[i]`.
# Interval 0 is implicitly `-Infinity < x < threshold[0]`. A value falling into
# a given interval is mapped to a colour specified for that interval.
#
# A colour scale is defined by a list of objects. Each list item must
# have values for
#
#   `threshold`: Upper limit of numerical interval.
#   `color`: Colour a value in the interval is rendered as/
#
# Each colour scale list item may also specify values that affect how the
# colour scale graphic (but not station data markers) is rendered:
#
#   `blockStyle`: CSS styles applied to colour block
#   `labelStyle`: CSS styles applied to label rendered below and centered on
#     the right-hand edge of colour block
#   `annotation`: string rendered inside colour block
#   `annotationStyle`: CSS styles applied to annotation
#
# See below for some examples of how these are used.
colourScales:
  precip:
    anomaly:
      - threshold: -0.875
        color: "rgba(140,81,10,0.75)"
      - threshold: -0.625
        color: "rgba(191,129,45,0.75)"
      - threshold: -0.375
        color: "rgba(223,194,125,0.75)"
      - threshold: -0.125
        color: "rgba(246,232,195,0.75)"
      - threshold: 0.125
        color: "rgba(245,245,245,0.75)"
      - threshold: 0.375
        color: "rgba(199,234,229,0.75)"
      - threshold: 1.125
        color: "rgba(128,205,193,0.75)"
      - threshold: 3.375
        color: "rgba(53,151,143,0.75)"
      - threshold: 10
        color: "rgba(1,102,94,0.75)"
      - threshold: +Infinity
        color: "rgba(253,187,213,0.75)"
        labelStyle:
          display: none
        blockStyle:
          borderLeft: "3px solid white"
          borderRight: "3px solid white"
          borderRadius: "1em"
        annotation: "erroneous"
    monthly:
      - threshold: 1000
        color: "rgba(54,255,50,0.8)"
        blockStyle:
          width: "20%"
        annotation: all other data values
      - threshold: +Infinity
        color: "rgba(253,187,213,0.75)"
        blockStyle:
          width: "10%"
          borderLeft: "3px solid white"
          borderRight: "3px solid white"
          borderRadius: "1em"
        labelStyle:
          display: none
        annotation: "erroneous"

    baseline:
      - threshold: +Infinity
        color: "rgba(54,255,50,0.8)"
        blockStyle:
          width: "20%"
        labelStyle:
          display: none
        annotation: all data values
  tmin:
    anomaly:
      - threshold: -4.5
        color: "rgba(5,48,97,0.75)"
      - threshold: -3.5
        color: "rgba(33,102,172,0.75)"
      - threshold: -2.5
        color: "rgba(67,147,195,0.75)"
      - threshold: -1.5
        color: "rgba(146,197,222,0.75)"
      - threshold: -0.5
        color: "rgba(209,229,240,0.75)"
      - threshold: 0.5
        color: "rgba(247,247,247,0.75)"
      - threshold: 1.5
        color: "rgba(253,219,199,0.75)"
      - threshold: 2.5
        color: "rgba(244,165,130,0.75)"
      - threshold: 3.5
        color: "rgba(214,96,77,0.75)"
      - threshold: 4.5
        color: "rgba(178,24,43,0.75)"
      - threshold: +Infinity
        color: "rgba(103,0,31,0.75)"
        labelStyle:
          display: none
    monthly:
      - threshold: +Infinity
        color: "rgba(51,136,255,0.8)"
        blockStyle:
          width: "20%"
        labelStyle:
          display: none
        annotation: all data values
    baseline:
      - threshold: +Infinity
        color: "rgba(51,136,255,0.8)"
        blockStyle:
          width: "20%"
        labelStyle:
          display: none
        annotation: all data values
  tmax:
    anomaly:
      - threshold: -4.5
        color: "rgba(5,48,97,0.75)"
      - threshold: -3.5
        color: "rgba(33,102,172,0.75)"
      - threshold: -2.5
        color: "rgba(67,147,195,0.75)"
      - threshold: -1.5
        color: "rgba(146,197,222,0.75)"
      - threshold: -0.5
        color: "rgba(209,229,240,0.75)"
      - threshold: 0.5
        color: "rgba(247,247,247,0.75)"
      - threshold: 1.5
        color: "rgba(253,219,199,0.75)"
      - threshold: 2.5
        color: "rgba(244,165,130,0.75)"
      - threshold: 3.5
        color: "rgba(214,96,77,0.75)"
      - threshold: 4.5
        color: "rgba(178,24,43,0.75)"
      - threshold: +Infinity
        color: "rgba(103,0,31,0.75)"
        labelStyle:
          display: none
    monthly:
      - threshold: +Infinity
        color: "rgba(255,104,49,0.8)"
        blockStyle:
          width: "20%"
        labelStyle:
          display: none
        annotation: all data values
    baseline:
      - threshold: +Infinity
        color: "rgba(255,104,49,0.8)"
        blockStyle:
          width: "20%"
        labelStyle:
          display: none
        annotation: all data values

# The ui object determines (some of) how various non-map UI components are
# rendered.
#
# Contents of `styling.buttons` objects are passed as arguments to
# the relevant React Bootstrap components (buttons and button groups).
#
ui:
  variableSelector:
    # Default variable on startup
    initial: precip # precip | tmin | tmax
    # Styling of variable selector control
    styling:
      buttons:
        vertical: true
        size: sm
        variant: outline-dark
  datasetSelector:
    # Default dataset on startup
    initial: anomaly # anomaly | monthly | baseline
    # Styling of dataset selector control
    styling:
      buttons:
        vertical: true
        size: sm
        variant: outline-dark
  monthIncrementDecrement:
    # Available values in month increment-/decrement-by dropdown
    by: [1, 3, 6]
    # Initial month increment-by value
    defaultBy: 1
    # Styling of month increment-decrement buttons
    styling:
      buttons:
        size: sm
        variant: outline-dark
  yearIncrementDecrement:
    # Available values in month increment-/decrement-by dropdown
    by: [1, 2, 3, 4, 5, 10]
    # Initial year increment-by value
    defaultBy: 1
    # Styling of year increment-decrement buttons
    styling:
      buttons:
        size: sm
        variant: outline-dark

backends:
  # URL of weather anomaly data service backend
  weatherAnomalyDataService: |
    https://services.pacificclimate.org/weather-anomaly/weather/monthly

help:
  offcanvas:
    - placement: end
      style:
        width: 600
      title: Quick How-To
      body: |
        To view the monthly anomaly, observation, or baseline value of a weather variable for a particular month and year:

        1. Click the weather variable of interest (**Precipitation**, **T<sub>min</sub>**, or **T<sub>max</sub>**).
        2. Click the value type of interest (**Anomaly**, **Monthly**, or **Baseline**).
        3. Use the date sliders to choose the month and year of interest. (For baseline values, only the month is selectable, since the baseline is a multi-year average of the selected month.)
        4. The map displays markers at each station representing the data values corresponding to those selections.
        5. Look at the colour bar at the top of the map to get an idea of what data ranges the colours represent.
        6. Click on a map marker to see station metadata (name, location, etc.) and precise anomaly data values for that station.

    - placement: end
      style:
        width: 600
      title: Selectors
      body: |
        The selectors on the right-hand side determine what is displayed on the map. They are intended to read as an English sentence of the form "Display `<observation variable>` `<value type>` for `<period>`." A couple of examples of this sentence:

          - Display T<sub>min</sub> Anomaly for Jun 2020.
          - Display Precipitation Baseline for Feb.
          
        Selectors 

        _Variable_: To select the observation variable, click on one of the three buttons labelled **Precipitation**, **T<sub>min</sub>**, or **T<sub>max</sub>**. The selected button is highlighted.

        _Value type_: To select the value type shown, click on one of the three buttons labelled **Anomaly**, **Monthly**, or **Baseline**.

        _Month_: To select the period month, click or drag the top slider to the desired month.

          - To decrement or increment the month selected, click the **-_N_** or **+_N_** button below the month slider. (_N_ here is the number of months by which to change the selection. The default is 1 month, so the buttons are labelled **-1** and **+1**.)
          - To change the increment, use the drop-down between the buttons.
          - These buttons can be useful to step uniformly through the months available while looking at the map.
          - Note that decrementing or incrementing the month carries across year boundaries. For example, incrementing +1 from Dec 2020 changes the selection to Jan 2021.

        _Year_: To select the period year, click or drag the top slider to the desired year.

          - To decrement or increment the year selected, click the **-_N_** or **+_N_** button below the year slider. (_N_ here is the number of years by which to change the selection. The default is 1 year, so the buttons are labelled **-1** and **+1**.)
          - To change the increment, use the drop-down between the buttons.
          - These buttons can be useful to step uniformly through the years available while looking at the map.

    - placement: start
      style:
        width: 600
      title: Map
      body: |
        ## Map display

        The map display consists of several parts. From top to bottom, roughly:

          - _Title_: Indicates the variable, value, and units displayed by the coloured markers.
          - _Colour scale_: Indicates the value ranges represented by the marker colours on the map.
          - _Base map_: A low-colour, unobtrusive map of the region covered by the database, designed to allow marker colours to be read easily.
          - _Zoom in/out controls_: (Upper left of map) These are also controlled by the mouse scroll wheel.
          - _Marker visibility control_: (Upper right of map) Selects which of the three types of markers to display on the map: anomaly, monthly station, and/or baseline station. See below for details.
          - _Markers_: A coloured circle or black dot centred on the location of each station with data, representing the data at that station. Click on a marker to see station and data details. See below for details.

        ### Map markers
          
        The central feature of the map is of course the markers, which represent data at each station.

        There are three categories of markers:

          - _Baseline data markers_: A small black dot at the location of each station for which there is baseline data for the selected variable and month.
          - _Monthly data markers_: A small black dot at the location of each station for which there is monthly data for the selected variable, month and year.
          - _Data value markers_: A coloured circle at the location of each station for which there is data (of the selected value type) for the selected variable, month and year.

        Baseline markers and monthly data markers do not differ in appearance. They can be shown or hidden (the default) using the map layer control in the upper right of the map. When displayed, they give an idea of the spatial extents of data available to form anomaly values. Anomalies can only be computed where there is both baseline and monthly data available.

        Each data value marker is filled with a colour representing the value of the anomaly at that station. The meaning (value range) of each colour is shown in the colour bar above the map. See below for more details.

        A data value marker can be clicked to show a pop-up that displays information on the station proper (its network, identity, location, etc.) and the data values for the selected variable and time period at that station. See below for more details.

        ### Data value popups

        A data value popup contains the following information:

          - Station metadata
              - Station name
              - Network the station belongs to
              - Station native ID: a unique station identifier provided by the network
              - Location and elevation
          - Data
              - Variable name (e.g., Precipitation)
              - Data values: One or more of the following items, depending on the value type selected (anomaly, monthly, baseline):
                   - Anomaly: absolute difference from baseline
                   - Departure: relative difference from baseline
                   - Baseline: absolute baseline value
                   - Monthly statistic: absolute value of monthly statistic (varies by variable: cumulative for precipitation; average for temperature)
                   - Data coverage: Fraction of contributing observations present in database relative to total number possible in selected period (month)

          ### Marker colours: colour bar and colour scales

          Colour scales (displayed in the colour bar at the top of the map) have been defined primarily for the anomaly values. At present, a single colour is used to represent all values in the Monthly and Baseline displays on the map.
          
          For Precipitation Anomaly values, a marker colour has been defined for computed anomalies that are apparently erroneous. These are the result of station variable reports that cannot at present be handled by the anomaly computations. (These are cumulative tipping-bucket sensor values which reset on irregular schedules. We are working on a fix for this problem.)
          
          ### Marker visibility
          
          The marker layer control in the upper right of the map allows you to select which of the three marker types are visible. Normally only the data value markers are of interest, and this is the default. If you are interested in where all baseline and/or where all monthly data value stations are located, you can display these markers too.
          
          ### Map zooming and scrolling
          
          To zoom in or out, use the controls in the upper left of the map, or use the mouse scroll wheel. To pan, click and drag on a point on the map.

    - placement: end
      style:
        width: 600
      title: Notes
      body: |
        ## General
        - Data acquisition is as close to real-time as possible given the sources. Same-day data is _not_ available on all networks.
        - Some stations report precipitation values in a format that causes the WAV to compute erroneous values. These values are flagged by a contrasting colour different from the normal data range colours. These values occur more often in recent years than in past years (prior to 2020). We are working to correct this problem.
        - When initially loaded into your web browser, the WAV sometimes displays an endless waiting spinner on the map. To fix this, please refresh the page.
        - If you choose a date in the future, the map displays an endless waiting spinner. Please choose a date prior to the current date.

        ## Weather anomalies
          
        A weather anomaly is a measure, at a given station, of the departure of weather observations for a given variable (e.g. total precipitation) over a given period (e.g., a specific month) from a historical baseline value for that period at that station.

        - The periods available are calendar months.
        - The variables available are total precipitation, average minimum temperature, and average maximum temperature over the period.

        Anomaly values are differences from baseline. They are expressed as follows:

          - For (total period) precipitation, as a percentage difference from baseline.
          - For average temperatures, as absolute difference in temperature from baseline.
          
        With the WAV, you can display not only anomaly values, but also the absolute period values and the baseline values used to derive the anomaly values.

        Note that baseline values are multi-year (1971-2000) averages for a given period (month).
