frontend:
  title: Weather Anomaly Viewer

  map:
    markers:
      location:
        color: '#222222'
        radius: 1
        weight: 1
        fillOpacity: 1
      data:
        radius: 8
        color: "#999999"
        weight: 1
        fillOpacity: 0.75
        fillColor: "#000000"  # Replaced according to station value

  colourScales:
    precip:
      anomaly:
        - threshold: -0.875
          color: '#8c510a'
        - threshold: -0.625
          color: '#bf812d'
        - threshold: -0.375
          color: '#dfc27d'
        - threshold: -0.125
          color: '#f6e8c3'
        - threshold: 0.125
          color: '#f5f5f5'
        - threshold: 0.375
          color: '#c7eae5'
        - threshold: 1.125
          color: '#80cdc1'
        - threshold: 3.375
          color: '#35978f'
        - threshold: 10
          color: '#01665e'
        - threshold: +Infinity
          color: '#fdbbd5'
          labelStyle:
            display: none
          blockStyle:
            borderLeft: "3px solid white"
            borderRight: "3px solid white"
            borderRadius: "1em"
          annotation: "erroneous"
      monthly:
        - threshold: +Infinity
          color: '#36ff32'
          labelStyle:
              display: none
          annotation: all data values
      baseline:
        - threshold: +Infinity
          color: '#36ff32'
          labelStyle:
            display: none
          annotation: all data values
    tmin:
      anomaly:
        - threshold: -4.5
          color: '#053061'
        - threshold: -3.5
          color: '#2166ac'
        - threshold: -2.5
          color: '#4393c3'
        - threshold: -1.5
          color: '#92c5de'
        - threshold: -0.5
          color: '#d1e5f0'
        - threshold: 0.5
          color: '#f7f7f7'
        - threshold: 1.5
          color: '#fddbc7'
        - threshold: 2.5
          color: '#f4a582'
        - threshold: 3.5
          color: '#d6604d'
        - threshold: 4.5
          color: '#b2182b'
        - threshold: +Infinity
          color: '#67001f'
          labelStyle:
            display: none
      monthly:
        - threshold: +Infinity
          color: '#3388ff'
          labelStyle:
            display: none
          annotation: all data values
      baseline:
        - threshold: +Infinity
          color: '#3388ff'
          labelStyle:
            display: none
          annotation: all data values
    tmax:
      anomaly:
        - threshold: -4.5
          color: '#053061'
        - threshold: -3.5
          color: '#2166ac'
        - threshold: -2.5
          color: '#4393c3'
        - threshold: -1.5
          color: '#92c5de'
        - threshold: -0.5
          color: '#d1e5f0'
        - threshold: 0.5
          color: '#f7f7f7'
        - threshold: 1.5
          color: '#fddbc7'
        - threshold: 2.5
          color: '#f4a582'
        - threshold: 3.5
          color: '#d6604d'
        - threshold: 4.5
          color: '#b2182b'
        - threshold: +Infinity
          color: '#67001f'
          labelStyle:
            display: none
      monthly:
        - threshold: +Infinity
          color: '#ff6831'
          labelStyle:
            display: none
          annotation: all data values
      baseline:
        - threshold: +Infinity
          color: '#ff6831'
          labelStyle:
            display: none
          annotation: all data values

backends:
  weatherAnomalyDataService: |
    https://services.pacificclimate.org/dev/weather-anomaly