name: Node CI

on: push

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: 22
      - name: Node.js Test Suite
        run: |
          npm install
          npm run build
          npm test
